security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
          pattern:        ^/
          switch_user:    true
          anonymous:      true
          form_login:
              provider:   fos_userbundle
              login_path: /login
              csrf_provider: form.csrf_provider
              default_target_path: /
          logout:
              path:       /logout

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/my-rides, role: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY] }              
        - { path: ^/profile, role: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY] }  
        - { path: ^/account-info, role: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY] }              
        - { path: ^/offer-ride/new/, role: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY] }              