<?php

namespace Proxies\__CG__\Tawsella\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AccountInfo extends \Tawsella\CoreBundle\Entity\AccountInfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'firstName', 'lastName', 'dateOfBirth', 'rate', 'carType', 'mobile', 'facebookUrl', 'twitterUrl', 'googlePlusUrl', 'music', 'pets', 'smoking', 'image', 'user');
        }

        return array('__isInitialized__', 'id', 'firstName', 'lastName', 'dateOfBirth', 'rate', 'carType', 'mobile', 'facebookUrl', 'twitterUrl', 'googlePlusUrl', 'music', 'pets', 'smoking', 'image', 'user');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AccountInfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function deleteImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deleteImage', array($image));

        return parent::deleteImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfBirth($dateOfBirth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfBirth', array($dateOfBirth));

        return parent::setDateOfBirth($dateOfBirth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfBirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfBirth', array());

        return parent::getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setRate($rate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRate', array($rate));

        return parent::setRate($rate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRate', array());

        return parent::getRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarType($carType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarType', array($carType));

        return parent::setCarType($carType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarType', array());

        return parent::getCarType();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookUrl($facebookUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookUrl', array($facebookUrl));

        return parent::setFacebookUrl($facebookUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookUrl', array());

        return parent::getFacebookUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitterUrl($twitterUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitterUrl', array($twitterUrl));

        return parent::setTwitterUrl($twitterUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitterUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitterUrl', array());

        return parent::getTwitterUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setGooglePlusUrl($googlePlusUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGooglePlusUrl', array($googlePlusUrl));

        return parent::setGooglePlusUrl($googlePlusUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getGooglePlusUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGooglePlusUrl', array());

        return parent::getGooglePlusUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Tawsella\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setMusic($music)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMusic', array($music));

        return parent::setMusic($music);
    }

    /**
     * {@inheritDoc}
     */
    public function getMusic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMusic', array());

        return parent::getMusic();
    }

    /**
     * {@inheritDoc}
     */
    public function setPets($pets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPets', array($pets));

        return parent::setPets($pets);
    }

    /**
     * {@inheritDoc}
     */
    public function getPets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPets', array());

        return parent::getPets();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmoking($smoking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmoking', array($smoking));

        return parent::setSmoking($smoking);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmoking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmoking', array());

        return parent::getSmoking();
    }

}
